"""Core neurosymbolic backend prototype for an 8-12 player Mafia game.

The engine is intentionally split into two paths:

* Fast path: a deterministic, CPU-only finite-state machine that owns every
  authoritative rule, matrix update, role action, vote, death, reveal, and win
  condition. This is the only path allowed to decide who is frozen, checked,
  healed, killed, exiled, or revealed.
* Slow path: an optional, mockable llama-cpp-python adapter that converts chat
  text into bounded mathematical deltas. The LLM never receives hidden global
  state and never returns game actions; it only returns JSON matching a strict
  schema.

The implementation favors integration-readiness over visual output. It exposes
plain Python objects, deterministic hooks, and async chat batching that can be
wired into a websocket/API layer later.
"""

from __future__ import annotations

import asyncio
import json
import random
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Iterable, Literal, Mapping, MutableMapping, Sequence

PlayerId = int
Gender = Literal["male", "female"]

MIN_PLAYERS = 8
MAX_PLAYERS = 12
NIGHT_DURATION_SECONDS = 30.0
DAY_DURATION_SECONDS = 45.0


class Role(str, Enum):
    """Public role labels used by the rules engine and avatar reveal logic."""

    CITIZEN = "Citizen"
    MAFIA = "Mafia"
    BOSS = "Boss"
    MANIAC = "Maniac"
    COP = "Cop"
    DOC = "Doc"
    WITNESS = "Witness"


class Phase(str, Enum):
    """Finite states for the authoritative game loop."""

    NIGHT = "night"
    DAY = "day"
    FINISHED = "finished"


class Team(str, Enum):
    """Victory buckets used for win-condition checks."""

    TOWN = "town"
    MAFIA = "mafia"
    MANIAC = "maniac"


class EventType(str, Enum):
    """Deterministic event codex keys for fast-path routing."""

    VOTE_AGAINST = "VOTE_AGAINST"
    WITNESS_REVEAL = "WITNESS_REVEAL"
    COP_CHECK = "COP_CHECK"
    BOSS_FREEZE = "BOSS_FREEZE"
    NIGHT_KILL = "NIGHT_KILL"
    DOC_HEAL = "DOC_HEAL"
    DAY_EXILE = "DAY_EXILE"
    PUBLIC_ROLE_REVEAL = "PUBLIC_ROLE_REVEAL"


@dataclass(slots=True)
class Psychotype:
    """Stable personality constants used to bias fast-path decisions.

    Values are normalized to [0, 1]. They are intentionally not generated by the
    LLM, because bot personality must remain stable and auditable.
    """

    stubbornness: float
    conformity: float
    aggression: float


@dataclass(slots=True)
class MafiaBot:
    """Authoritative state tracker for one player/bot.

    The matrices are keyed by target player id. They include self entries to
    keep vector operations simple, but decision helpers ignore self when
    selecting targets.
    """

    bot_id: PlayerId
    gender: Gender
    role: Role
    psychotype: Psychotype
    suspicion_matrix: dict[PlayerId, float] = field(default_factory=dict)
    empathy_matrix: dict[PlayerId, float] = field(default_factory=dict)
    stress_level: float = 0.0
    is_frozen: bool = False
    is_alive: bool = True
    avatar_state: str = ""
    public_role: Role | None = None

    def __post_init__(self) -> None:
        if self.gender not in {"male", "female"}:
            raise ValueError(f"Unsupported gender: {self.gender!r}")
        self.avatar_state = self.avatar_state or f"default_{self.gender}"

    @property
    def team(self) -> Team:
        if self.role in {Role.MAFIA, Role.BOSS}:
            return Team.MAFIA
        if self.role is Role.MANIAC:
            return Team.MANIAC
        return Team.TOWN

    def reveal_role(self, role: Role | None = None) -> None:
        """Update public role and avatar after a deterministic reveal event."""

        revealed = role or self.role
        self.public_role = revealed
        self.avatar_state = f"{revealed.value.lower()}_{self.gender}"


@dataclass(frozen=True, slots=True)
class ChatMessage:
    """One public chat message waiting for slow-path interpretation."""

    speaker_id: PlayerId
    text: str
    visible_to: tuple[PlayerId, ...]


@dataclass(slots=True)
class LLMChatDelta:
    """Strict, bounded schema returned by the slow path.

    d_suspicion and d_empathy map mentioned/affected target ids to deltas. The
    parser clamps all values so even a malformed/malicious model response cannot
    break matrix ranges.
    """

    reasoning_chain: str
    d_suspicion: dict[PlayerId, float]
    d_empathy: dict[PlayerId, float]
    stress_impact: float


@dataclass(slots=True)
class NightResolution:
    frozen_target: PlayerId | None = None
    mafia_target: PlayerId | None = None
    maniac_target: PlayerId | None = None
    doc_target: PlayerId | None = None
    cop_target: PlayerId | None = None
    witness_observed_killer: PlayerId | None = None
    deaths: list[PlayerId] = field(default_factory=list)


@dataclass(slots=True)
class GameState:
    """Mutable authoritative game state owned by the fast-path router."""

    bots: dict[PlayerId, MafiaBot]
    phase: Phase = Phase.NIGHT
    day_index: int = 1
    night_index: int = 1
    rng: random.Random = field(default_factory=random.Random)
    event_log: list[str] = field(default_factory=list)
    winner: Team | None = None

    def __post_init__(self) -> None:
        if not MIN_PLAYERS <= len(self.bots) <= MAX_PLAYERS:
            raise ValueError(f"Game requires {MIN_PLAYERS}-{MAX_PLAYERS} players")
        ids = set(self.bots)
        for bot in self.bots.values():
            missing_suspicion = ids - set(bot.suspicion_matrix)
            missing_empathy = ids - set(bot.empathy_matrix)
            for target_id in missing_suspicion:
                bot.suspicion_matrix[target_id] = 0.0
            for target_id in missing_empathy:
                bot.empathy_matrix[target_id] = 0.0

    def alive_bots(self) -> list[MafiaBot]:
        return [bot for bot in self.bots.values() if bot.is_alive]

    def alive_ids(self, *, exclude: PlayerId | None = None) -> list[PlayerId]:
        return [bot.bot_id for bot in self.alive_bots() if bot.bot_id != exclude]

    def by_role(self, role: Role) -> list[MafiaBot]:
        return [bot for bot in self.alive_bots() if bot.role is role]


def clamp(value: float, lower: float, upper: float) -> float:
    return max(lower, min(upper, value))


def add_clamped(matrix: MutableMapping[PlayerId, float], target_id: PlayerId, delta: float, lower: float, upper: float) -> None:
    matrix[target_id] = clamp(matrix.get(target_id, 0.0) + delta, lower, upper)


def first_impression_init(state: GameState, jitter: float = 0.08) -> None:
    """Seed mild initial matrix noise so Day 1 voting is not silent/random.

    The signal is deliberately small and symmetric enough to avoid deciding the
    game by RNG. It only creates enough variance for opening accusations.
    """

    for observer in state.bots.values():
        for target_id in state.bots:
            if observer.bot_id == target_id:
                observer.suspicion_matrix[target_id] = 0.0
                observer.empathy_matrix[target_id] = 0.0
                continue
            observer.suspicion_matrix[target_id] = clamp(state.rng.uniform(0.02, jitter), 0.0, 1.0)
            observer.empathy_matrix[target_id] = clamp(state.rng.uniform(-jitter, jitter), -1.0, 1.0)


class EventCodex:
    """Deterministic event router for fast-path psychological updates."""

    def apply(self, state: GameState, event_type: EventType, actor_id: PlayerId | None = None, target_id: PlayerId | None = None) -> None:
        if event_type is EventType.VOTE_AGAINST:
            self._vote_against(state, actor_id, target_id)
        elif event_type is EventType.WITNESS_REVEAL:
            self._witness_reveal(state, target_id)
        elif event_type is EventType.PUBLIC_ROLE_REVEAL:
            self._public_role_reveal(state, target_id)
        elif event_type is EventType.BOSS_FREEZE and target_id is not None:
            state.bots[target_id].is_frozen = True
            state.event_log.append(f"Boss froze player {target_id}")
        elif event_type is EventType.NIGHT_KILL and target_id is not None:
            state.bots[target_id].is_alive = False
            self._public_role_reveal(state, target_id)
            state.event_log.append(f"Player {target_id} died at night")
        elif event_type is EventType.DAY_EXILE and target_id is not None:
            state.bots[target_id].is_alive = False
            self._public_role_reveal(state, target_id)
            state.event_log.append(f"Player {target_id} was exiled by vote")
        elif event_type is EventType.COP_CHECK:
            state.event_log.append(f"Cop checked player {target_id}")
        elif event_type is EventType.DOC_HEAL:
            state.event_log.append(f"Doctor protected player {target_id}")
        else:
            raise ValueError(f"Unhandled or malformed event: {event_type}")

    def _vote_against(self, state: GameState, actor_id: PlayerId | None, target_id: PlayerId | None) -> None:
        if actor_id is None or target_id is None or actor_id == target_id:
            return
        actor = state.bots[actor_id]
        target = state.bots[target_id]
        add_clamped(target.empathy_matrix, actor_id, -0.12, -1.0, 1.0)
        add_clamped(actor.suspicion_matrix, target_id, 0.04, 0.0, 1.0)

        for observer in state.alive_bots():
            if observer.bot_id in {actor_id, target_id}:
                continue
            observer_trusts_actor = observer.empathy_matrix.get(actor_id, 0.0) - observer.suspicion_matrix.get(actor_id, 0.0)
            if observer_trusts_actor >= 0.0:
                add_clamped(observer.suspicion_matrix, target_id, 0.03, 0.0, 1.0)
            else:
                add_clamped(observer.suspicion_matrix, actor_id, 0.03, 0.0, 1.0)
        state.event_log.append(f"Player {actor_id} voted against {target_id}")

    def _witness_reveal(self, state: GameState, killer_id: PlayerId | None) -> None:
        if killer_id is None:
            return
        killer = state.bots[killer_id]
        killer.reveal_role()
        for observer in state.alive_bots():
            if observer.role in {Role.CITIZEN, Role.COP, Role.DOC, Role.WITNESS}:
                observer.suspicion_matrix[killer_id] = 1.0
                add_clamped(observer.empathy_matrix, killer_id, -0.75, -1.0, 1.0)
        state.event_log.append(f"Witness publicly revealed killer {killer_id}")

    def _public_role_reveal(self, state: GameState, target_id: PlayerId | None) -> None:
        if target_id is None:
            return
        state.bots[target_id].reveal_role()


class LlamaJSONEvaluator:
    """llama-cpp-python slow-path evaluator for public chat psychology.

    The evaluator owns local Qwen inference, validates JSON-shaped output, and
    returns only bounded matrix deltas. It intentionally has no API for role
    actions, votes, deaths, reveals, or win conditions. Tests may pass a fake
    `llm` object with a compatible `create_chat_completion` method.
    """

    MODEL_PATH = "./qwen2.5-3b-instruct-q4_k_m.gguf"
    JSON_SCHEMA: dict[str, Any] = {
        "type": "object",
        "properties": {
            "reasoning_chain": {"type": "string"},
            "d_suspicion": {"type": "object", "additionalProperties": {"type": "number"}},
            "d_empathy": {"type": "object", "additionalProperties": {"type": "number"}},
            "stress_impact": {"type": "number"},
        },
        "required": ["reasoning_chain", "d_suspicion", "d_empathy", "stress_impact"],
    }

    SYSTEM_PROMPT = (
        "[SYSTEM] You are the Slow Path psychological evaluator for a Mafia "
        "social deduction game. Evaluate only the psychological impact of the "
        "speaker's public text on listeners. Return strict JSON matching the "
        "provided schema. Use player-id keys such as '1' or '7'. Values in "
        "d_suspicion, d_empathy, and stress_impact MUST be between -0.5 and "
        "0.5. Positive d_suspicion means listeners become more suspicious of "
        "that target. Positive d_empathy means listeners become more sympathetic "
        "to that target. You must never decide votes, night actions, deaths, "
        "role reveals, healing, investigations, or win conditions."
    )

    def __init__(self, llm: Any | None = None, model_path: str = MODEL_PATH) -> None:
        if llm is not None:
            self.llm = llm
            return

        from llama_cpp import Llama

        self.llm = Llama(
            model_path=model_path,
            n_gpu_layers=-1,
            n_ctx=4096,
            verbose=False,
        )

    async def evaluate_chat_message(self, speaker_id: PlayerId, text: str, listeners_context: Mapping[str, Any]) -> LLMChatDelta:
        """Infer bounded psychological deltas from one public chat message."""

        prompt = self._build_prompt(speaker_id, text, listeners_context)
        raw = await asyncio.to_thread(
            self.llm.create_chat_completion,
            messages=[
                {"role": "system", "content": self.SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object", "schema": self.JSON_SCHEMA},
            temperature=0.1,
        )
        content = raw["choices"][0]["message"]["content"]
        return self._parse_delta(content)

    async def generate_bot_chat(self, bot: MafiaBot, public_context: Mapping[str, Any]) -> str:
        """Generate one short, non-authoritative bot utterance for the CLI."""

        prompt = (
            "Write one short in-character public Mafia chat sentence for this bot. "
            "Do not reveal hidden roles. Do not choose a final vote. The sentence "
            "may defend, accuse, or express uncertainty based only on public context.\n"
            f"Bot: P{bot.bot_id}; stress={bot.stress_level:.2f}; public_context="
            f"{json.dumps(public_context, ensure_ascii=False)}"
        )
        raw = await asyncio.to_thread(
            self.llm.create_chat_completion,
            messages=[
                {"role": "system", "content": "[SYSTEM] Generate flavor chat only. Never decide game actions."},
                {"role": "user", "content": prompt},
            ],
            temperature=0.7,
            max_tokens=48,
        )
        return str(raw["choices"][0]["message"]["content"]).strip().replace("\n", " ")[:180]

    def _build_prompt(self, speaker_id: PlayerId, text: str, listeners_context: Mapping[str, Any]) -> str:
        return (
            "Evaluate the public chat message below into numeric deltas only.\n"
            f"Speaker: P{speaker_id}\n"
            f"Public text: {text!r}\n"
            "Listener-local context JSON, containing only public/allowed fields: "
            f"{json.dumps(listeners_context, ensure_ascii=False)}"
        )

    def _parse_delta(self, content: str) -> LLMChatDelta:
        payload = json.loads(content)
        return LLMChatDelta(
            reasoning_chain=str(payload.get("reasoning_chain", ""))[:500],
            d_suspicion=self._parse_delta_map(payload.get("d_suspicion", {})),
            d_empathy=self._parse_delta_map(payload.get("d_empathy", {})),
            stress_impact=clamp(float(payload.get("stress_impact", 0.0)), -0.5, 0.5),
        )

    def _parse_delta_map(self, raw_map: Mapping[str, Any]) -> dict[PlayerId, float]:
        parsed: dict[PlayerId, float] = {}
        for raw_key, raw_value in raw_map.items():
            key = str(raw_key).strip().removeprefix("P").removeprefix("p")
            if not key.isdigit():
                continue
            parsed[int(key)] = clamp(float(raw_value), -0.5, 0.5)
        return parsed


class NeurosymbolicRouter:
    """Fast-path game router with async slow-path chat batching."""

    def __init__(self, state: GameState, evaluator: LlamaJSONEvaluator | None = None) -> None:
        self.state = state
        self.codex = EventCodex()
        self.evaluator = evaluator or LlamaJSONEvaluator()
        self._chat_queue: asyncio.Queue[ChatMessage] = asyncio.Queue()
        self.last_night_resolution: NightResolution | None = None
        self.last_day_votes: dict[PlayerId, PlayerId] = {}

    def queue_night_actions(self) -> NightResolution:
        """Resolve the deterministic night queue and store it for morning UI/CLI.

        This wrapper exists for integrations that treat night as queued role
        actions followed by a separate morning report. It delegates to the
        existing fast-path resolver and does not alter the underlying math.
        """

        self.last_night_resolution = self.resolve_night_phase()
        return self.last_night_resolution

    def apply_morning_report(self) -> NightResolution | None:
        """Return the latest resolved night summary for presentation layers."""

        return self.last_night_resolution

    async def enqueue_chat(self, speaker_id: PlayerId, text: str, visible_to: Iterable[PlayerId] | None = None) -> None:
        audience = tuple(visible_to or self.state.alive_ids(exclude=speaker_id))
        await self._chat_queue.put(ChatMessage(speaker_id=speaker_id, text=text, visible_to=audience))

    async def process_chat_batch(self, max_batch_size: int = 8) -> None:
        """Drain queued chat messages and apply LLM deltas via credibility."""

        batch: list[ChatMessage] = []
        while len(batch) < max_batch_size and not self._chat_queue.empty():
            batch.append(self._chat_queue.get_nowait())
        if not batch:
            return

        tasks = [self._evaluate_one_message(message) for message in batch]
        await asyncio.gather(*tasks)

    async def _evaluate_one_message(self, message: ChatMessage) -> None:
        context = {"speaker_id": message.speaker_id, "alive_target_ids": self.state.alive_ids(exclude=message.speaker_id)}
        delta = await self.evaluator.evaluate_chat_message(message.speaker_id, message.text, context)
        self._apply_chat_delta(message, delta)

    def _apply_chat_delta(self, message: ChatMessage, delta: LLMChatDelta) -> None:
        for listener_id in message.visible_to:
            listener = self.state.bots[listener_id]
            if not listener.is_alive:
                continue
            credibility = self._credibility_index(listener, message.speaker_id)
            for target_id, raw_delta in delta.d_suspicion.items():
                if target_id in self.state.bots and target_id != listener_id:
                    add_clamped(listener.suspicion_matrix, target_id, raw_delta * credibility, 0.0, 1.0)
            for target_id, raw_delta in delta.d_empathy.items():
                if target_id in self.state.bots and target_id != listener_id:
                    add_clamped(listener.empathy_matrix, target_id, raw_delta * credibility, -1.0, 1.0)
            listener.stress_level = clamp(listener.stress_level + abs(credibility) * delta.stress_impact, 0.0, 1.0)
        self.state.event_log.append(f"LLM deltas applied for speaker {message.speaker_id}")

    def _credibility_index(self, listener: MafiaBot, speaker_id: PlayerId) -> float:
        """Map trust to [-1, 1]; distrust inverts model deltas."""

        empathy = listener.empathy_matrix.get(speaker_id, 0.0)
        suspicion = listener.suspicion_matrix.get(speaker_id, 0.0)
        trust = empathy - suspicion
        resistance = listener.psychotype.stubbornness * 0.35
        return clamp(trust + 0.65 - resistance, -1.0, 1.0)

    async def run_phase_loop(self, *, night_seconds: float = NIGHT_DURATION_SECONDS, day_seconds: float = DAY_DURATION_SECONDS) -> Team | None:
        """Demonstrate the authoritative FSM loop.

        In production this would be driven by websocket/action events. Here the
        loop sleeps in short ticks, drains chat batches, and resolves phases when
        the timer expires. Night can end early because all actions are selected
        synchronously by deterministic role policies.
        """

        while self.state.phase is not Phase.FINISHED:
            if self.state.phase is Phase.NIGHT:
                await self.process_chat_batch()
                self.resolve_night_phase()
                self._advance_or_finish(Phase.DAY)
                continue

            deadline = asyncio.get_running_loop().time() + day_seconds
            while asyncio.get_running_loop().time() < deadline and self.state.phase is Phase.DAY:
                await self.process_chat_batch()
                await asyncio.sleep(0.05)
            self.resolve_day_phase()
            self._advance_or_finish(Phase.NIGHT)
        return self.state.winner

    def resolve_night_phase(self) -> NightResolution:
        """Resolve boss, mafia, maniac, doc, cop, and witness actions."""

        for bot in self.state.bots.values():
            bot.is_frozen = False

        resolution = NightResolution()
        resolution.frozen_target = self._select_boss_freeze_target()
        if resolution.frozen_target is not None:
            self.codex.apply(self.state, EventType.BOSS_FREEZE, target_id=resolution.frozen_target)

        resolution.mafia_target = self._select_mafia_consensus_target()
        resolution.maniac_target = self._select_maniac_target()
        resolution.doc_target = self._select_doc_target()
        resolution.cop_target = self._select_cop_check_target()

        if resolution.cop_target is not None:
            self.codex.apply(self.state, EventType.COP_CHECK, actor_id=self._first_alive_role_id(Role.COP), target_id=resolution.cop_target)
        if resolution.doc_target is not None:
            self.codex.apply(self.state, EventType.DOC_HEAL, actor_id=self._first_alive_role_id(Role.DOC), target_id=resolution.doc_target)

        attempted_kills = [target for target in [resolution.mafia_target, resolution.maniac_target] if target is not None]
        for target_id in Counter(attempted_kills):
            if target_id == resolution.doc_target:
                self.state.event_log.append(f"Player {target_id} survived due to doctor protection")
                continue
            if self.state.bots[target_id].is_alive:
                self.codex.apply(self.state, EventType.NIGHT_KILL, target_id=target_id)
                resolution.deaths.append(target_id)

        resolution.witness_observed_killer = self._witness_observation(resolution, attempted_kills)
        if resolution.witness_observed_killer is not None:
            self.codex.apply(self.state, EventType.WITNESS_REVEAL, target_id=resolution.witness_observed_killer)

        self.state.night_index += 1
        return resolution

    def resolve_day_phase(self) -> PlayerId | None:
        """Run deterministic vote based on suspicion matrices and freeze state."""

        votes: dict[PlayerId, PlayerId] = {}
        for voter in self.state.alive_bots():
            if voter.is_frozen:
                continue
            target = self._select_day_vote_target(voter)
            if target is not None:
                votes[voter.bot_id] = target
                self.codex.apply(self.state, EventType.VOTE_AGAINST, actor_id=voter.bot_id, target_id=target)

        self.last_day_votes = votes.copy()
        if not votes:
            self.state.event_log.append("Day ended with no valid votes")
            self.state.day_index += 1
            return None

        counts = Counter(votes.values())
        top_count = max(counts.values())
        tied = [target_id for target_id, count in counts.items() if count == top_count]
        exiled = self.state.rng.choice(tied)
        self.codex.apply(self.state, EventType.DAY_EXILE, target_id=exiled)
        self.state.day_index += 1
        return exiled

    def _select_day_vote_target(self, voter: MafiaBot) -> PlayerId | None:
        candidates = self.state.alive_ids(exclude=voter.bot_id)
        if not candidates:
            return None
        threshold = 0.18 - voter.psychotype.aggression * 0.08
        scored = [(voter.suspicion_matrix[target_id] - 0.25 * voter.empathy_matrix[target_id], target_id) for target_id in candidates]
        best_score, best_target = max(scored, key=lambda item: item[0])
        if best_score < threshold and self.state.day_index == 1:
            return None
        return best_target

    def _select_boss_freeze_target(self) -> PlayerId | None:
        bosses = self.state.by_role(Role.BOSS)
        if not bosses:
            return None
        boss = bosses[0]
        threats = [bot for bot in self.state.alive_bots() if bot.team is not Team.MAFIA and bot.bot_id != boss.bot_id]
        if not threats:
            return None
        role_priority = {Role.COP: 1.0, Role.DOC: 0.85, Role.WITNESS: 0.8, Role.MANIAC: 0.7, Role.CITIZEN: 0.35}
        return max(
            threats,
            key=lambda target: role_priority.get(target.role, 0.2)
            + boss.suspicion_matrix[target.bot_id]
            - 0.2 * boss.empathy_matrix[target.bot_id],
        ).bot_id

    def _select_mafia_consensus_target(self) -> PlayerId | None:
        mafia = [bot for bot in self.state.alive_bots() if bot.team is Team.MAFIA and not bot.is_frozen]
        candidates = [bot for bot in self.state.alive_bots() if bot.team is not Team.MAFIA]
        if not mafia or not candidates:
            return None

        scores: defaultdict[PlayerId, float] = defaultdict(float)
        role_threat = {Role.COP: 0.9, Role.DOC: 0.65, Role.WITNESS: 0.7, Role.MANIAC: 0.55, Role.CITIZEN: 0.25}
        for mafioso in mafia:
            for target in candidates:
                scores[target.bot_id] += role_threat.get(target.role, 0.2)
                scores[target.bot_id] += 0.4 * mafioso.suspicion_matrix[target.bot_id]
                scores[target.bot_id] -= 0.2 * mafioso.empathy_matrix[target.bot_id]
        return max(scores, key=scores.get)

    def _select_maniac_target(self) -> PlayerId | None:
        """Choose target maximizing U_x = -|N_Town_after - (N_Mafia_after + 1)|.

        The +1 keeps the maniac's preferred world near parity where neither town
        nor mafia runs away with the endgame. Tie-breakers prefer high suspicion
        and low empathy from the maniac's perspective.
        """

        maniacs = self.state.by_role(Role.MANIAC)
        if not maniacs or maniacs[0].is_frozen:
            return None
        maniac = maniacs[0]
        candidates = [bot for bot in self.state.alive_bots() if bot.bot_id != maniac.bot_id]
        if not candidates:
            return None

        def utility(target: MafiaBot) -> tuple[float, float]:
            town_after = sum(1 for bot in self.state.alive_bots() if bot.team is Team.TOWN and bot.bot_id != target.bot_id)
            mafia_after = sum(1 for bot in self.state.alive_bots() if bot.team is Team.MAFIA and bot.bot_id != target.bot_id)
            ux = -abs(town_after - (mafia_after + 1))
            personal_bias = maniac.suspicion_matrix[target.bot_id] - maniac.empathy_matrix[target.bot_id]
            return ux, personal_bias

        return max(candidates, key=utility).bot_id

    def _select_doc_target(self) -> PlayerId | None:
        docs = self.state.by_role(Role.DOC)
        if not docs or docs[0].is_frozen:
            return None
        doc = docs[0]
        candidates = self.state.alive_ids()
        return max(candidates, key=lambda target_id: doc.empathy_matrix[target_id] + doc.suspicion_matrix[target_id])

    def _select_cop_check_target(self) -> PlayerId | None:
        cops = self.state.by_role(Role.COP)
        if not cops or cops[0].is_frozen:
            return None
        cop = cops[0]
        candidates = self.state.alive_ids(exclude=cop.bot_id)
        return max(candidates, key=lambda target_id: cop.suspicion_matrix[target_id], default=None)

    def _witness_observation(self, resolution: NightResolution, attempted_kills: Sequence[PlayerId]) -> PlayerId | None:
        witnesses = self.state.by_role(Role.WITNESS)
        if not witnesses or witnesses[0].is_frozen or not attempted_kills:
            return None
        witness = witnesses[0]
        likely_killers = [resolution.mafia_target, resolution.maniac_target]
        observed = [killer for killer in likely_killers if killer is not None and killer != witness.bot_id]
        if not observed:
            return None
        # Prototype rule: witness reveals the first observed killer immediately.
        # A production game can defer this until the witness chooses to publish.
        return observed[0]

    def _first_alive_role_id(self, role: Role) -> PlayerId | None:
        bots = self.state.by_role(role)
        return bots[0].bot_id if bots else None

    def _advance_or_finish(self, next_phase: Phase) -> None:
        winner = self.check_win_condition()
        if winner is not None:
            self.state.phase = Phase.FINISHED
            self.state.winner = winner
            self.state.event_log.append(f"Winner: {winner.value}")
            return
        self.state.phase = next_phase

    def check_win_condition(self) -> Team | None:
        alive = self.state.alive_bots()
        mafia_count = sum(1 for bot in alive if bot.team is Team.MAFIA)
        town_count = sum(1 for bot in alive if bot.team is Team.TOWN)
        maniac_alive = any(bot.team is Team.MANIAC for bot in alive)
        if mafia_count == 0 and not maniac_alive:
            return Team.TOWN
        if mafia_count >= town_count + (1 if maniac_alive else 0):
            return Team.MAFIA
        if maniac_alive and mafia_count == 0 and town_count <= 1:
            return Team.MANIAC
        return None


def build_demo_state(seed: int = 7) -> GameState:
    """Create a valid 8-player state for smoke tests and integration examples."""

    rng = random.Random(seed)
    roles = [Role.BOSS, Role.MAFIA, Role.MANIAC, Role.COP, Role.DOC, Role.WITNESS, Role.CITIZEN, Role.CITIZEN]
    genders: list[Gender] = ["male", "female", "male", "male", "female", "female", "male", "female"]
    bots: dict[PlayerId, MafiaBot] = {}
    for bot_id, (role, gender) in enumerate(zip(roles, genders), start=1):
        bots[bot_id] = MafiaBot(
            bot_id=bot_id,
            gender=gender,
            role=role,
            psychotype=Psychotype(
                stubbornness=rng.uniform(0.2, 0.8),
                conformity=rng.uniform(0.2, 0.8),
                aggression=rng.uniform(0.2, 0.8),
            ),
        )
    state = GameState(bots=bots, rng=rng)
    first_impression_init(state)
    return state


async def demo_round() -> GameState:
    """Run one illustrative night/day cycle without any frontend dependency."""

    state = build_demo_state()
    router = NeurosymbolicRouter(state)
    await router.enqueue_chat(4, "P1 is suspicious, maybe mafia", visible_to=state.alive_ids(exclude=4))
    await router.enqueue_chat(5, "I trust P4, P3 feels unsafe", visible_to=state.alive_ids(exclude=5))
    await router.process_chat_batch()
    router.resolve_night_phase()
    router._advance_or_finish(Phase.DAY)
    if state.phase is Phase.DAY:
        router.resolve_day_phase()
        router._advance_or_finish(Phase.NIGHT)
    return state


if __name__ == "__main__":
    final_state = asyncio.run(demo_round())
    print("Phase:", final_state.phase.value)
    print("Winner:", final_state.winner.value if final_state.winner else None)
    print("Alive:", final_state.alive_ids())
    print("Events:")
    for event in final_state.event_log:
        print("-", event)
